# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b03a9e2f92db2a680d55fa7f58c23821a824b2d954daa680e4848ee30e0f541e30740ab0c0157b1e71e53c780fac41db2fcee797ed7cbfa5df2bf6b65d000901

test:
  secret_key_base: 8dd163090738868699dd92b45e66c8ecc7d928c207d0cb5139ae2087992f08b192908d356013471855451be4af79c6a56e8e55b0d60a3eb5a2fa9bd9579bc293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
